Added make objects function
htmlacademy-javascript/1696347-keksobooking-23 pull request #3
Opened 2021-06-10 23:00 UTC by ihidanaka

2021-06-11 06:23 UTC, AlexMasterov requested changes

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +const fillAds = (elementsAmount) => {
```diff
- (elementsAmount)
+ (count)
```

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +  adID.forEach((val, index) => adID[index] = index + 1);
adID.forEach((val, index) `=>` `adID[index] = index + 1`);

[`Д 27`](https://up.htmlacademy.ru/javascript/23/criteries#d27)
> Оператор присваивания (`=`) не используется как часть выражения

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +      address: `${LATITUDE},${LONGTITUDE}`,
См. задание:
> `address`, строка — адрес предложения. Для простоты пусть пока составляется из географических координат по маске `{{location.lat}}, {{location.lng}}`

```diff
- address: `${LATITUDE},${LONGTITUDE}`,
+ address: `${LATITUDE}, ${LONGTITUDE}`,
```

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +      price: getRandomInteger(0).toString(),
```
price: "3134834202563488"
```
Сейчас значение `price` является строкой.

См. задание:
> `price`, **число** — стоимость. Случайное целое положительное число

Нужно исправить.

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +      rooms: getRandomInteger(0).toString(),
```
rooms: "4638937575739048"
```
Сейчас значение `rooms` является строкой.

См. задание:
> `rooms`, **число** — количество комнат. Случайное целое положительное число

Нужно исправить.

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +      guests: getRandomInteger(0).toString(),
```
guests: "8346783597910752"
```
Сейчас значение `guests` является строкой.

См. задание:
> `guests`, **число** — количество гостей, которое можно разместить. Случайное целое положительное число

Нужно исправить.

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L6
https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L17
https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L21
</details>

Такое форматирование кода нетипично для языка JavaScript и его экосистемы.

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +const fillAds = (elementsAmount) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L102-L114
</details>

🤔

> Как вариант, генерировать уникальный идентификатор (`id`) вне функции (и передавать в качестве аргумента), например, на основе числового индекса массива

```js
const adverts = new Array(10).fill(null).map((_, idx) => createAdvert(idx + 1));
```
Или так:
```js
const adverts = Array.from({ length: 10 }, (_, idx) => createAdvert(idx + 1));
```

См. [Array.`from`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BE%D1%87%D0%BD%D0%BE%D0%B9_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_%D0%B8_array.from()).

2021-06-11 06:23 UTC, AlexMasterov commented on js/main.js
> +const getPhotosArray = (maxArrayLength) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L66
https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/185cf4061e45caaf3f3399945664e13c2c013412/js/main.js#L68
</details>

Здесь массив сначала заполняется _числами_, а потом _строками_ 🤔

> В других местах тоже самое

2021-06-16 19:51 UTC, ihidanaka commented on js/main.js
> +  adID.forEach((val, index) => adID[index] = index + 1);
Решит ли проблему ?

```suggestion
 advertIDs.forEach((value, index) =>{ let newIndex = index++; advertIDs[index] = newIndex;});
```

2021-06-16 21:49 UTC, AlexMasterov approved these changes
Задание выполнено, но с названиями проблема.

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const getRandomInteger = (min, max) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1696347-keksobooking-23/blob/fa0e5d50e9ff1d2eecdf06aed50017e8b926d4dd/js/main.js#L9-L11
</details>

[`Д 13`](https://up.htmlacademy.ru/javascript/23/criteries#d13)
> В проекте не должно быть избыточных проверок

Вместо `max === undefined` лучше добавить значение _по умолчанию_:

```diff
- const getRandomInteger = (min, max) => {
+ const getRandomInteger = (min, max = Number.MAX_SAFE_INTEGER) => {
```

`max === null`

Это лишние.

Функция ожидает, что значением `max` будет число, а здесь проверяется на `null`. Если функции при вызове в качестве аргумента явно передают `null`, то это проблема пользователя функции.

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +  if ((min < 0) || (max < 0)) {
👍🏻

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +  const LONGTITUDE = getRandomFloat(139.70000, 139.80000, 5); //Ругается es-lint если меняю на let
> Ругается es-lint если меняю на let

Зачем менять на `let`?

См. внимательно [прошлое замечание](https://github.com/htmlacademy-javascript/1696347-keksobooking-23/pull/3#discussion_r649706749):

> Названия переменных записаны в формате _констант_, но их **значения** с помощью `getRandomFloat` (= `Math.random()`) и таким образом **являются непостоянными**

[`Б 3`](https://up.htmlacademy.ru/javascript/23/criteries#b3)
> Названия переменных, параметров, свойств и методов **начинаются со строчной буквы и записываются в нотации `camelCase`**

Нужно записать обычной строкой, в нижним регистре.

> В языке с настоящими константами, например, в Rust, [нельзя создать константу для значения, которое получено генератором _случайных_ чисел](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c4ed55e404a3a4ab5ef8a560974bc6ba)

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const createAdvert = (index) => {
```diff
- const createAdvert = (index) => {
+ const createAdvert = (id) => {
```

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const getAdvertsArray = (count) => {
```diff
- const getAdvertsArray = (count) => {
+ const generateAdverts = (count) => {
```

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const getPhotosArray = (maxArrayLength) => {
```diff
- const getPhotosArray = (maxArrayLength) => {
+ const generatePhotos = (count) => {
```

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const shuffleArray = (arrays) => arrays.sort(() => Math.random() - 0.5);
```diff
- const shuffleArray = (arrays) => arrays.sort(() => Math.random() - 0.5);
+ const shuffleArray = (items) => items.sort(() => Math.random() - 0.5);
```

2021-06-16 21:49 UTC, AlexMasterov commented on js/main.js
> +const getAuthorAvatar = (arrayElement) => (arrayElement < 10) ? `img/avatars/user0${arrayElement}.png` : `img/avatars/user${arrayElement}.png`;
```diff
- const getAuthorAvatar = (arrayElement) => (arrayElement < 10)
+ const getAuthorAvatar = (id) => id < 10
```

2021-06-16 21:49 UTC, merged

2021-06-16 21:54 UTC, AlexMasterov commented on js/main.js
> +  adID.forEach((val, index) => adID[index] = index + 1);
> Решит ли проблему ?

Да, но только _формально_. Лучше избавиться от самого решения 😃